### ISSUE TITLE
How to use missing in Readme.md as well as not avaliable in /doc directory of the project.

### ISSUE THREAD

**Issue by kshithijiyer** [google/glazier#13]

**Comment by TsekNet** [comment]
Hi,

Can you clarify where you are seeing a missing readme in our documentation?

**Comment by kshithijiyer** [comment]
The documentation on "How to use" the project is missing.

**Comment by TsekNet** [comment]
Have you had a chance to look at our setup guide [here](https://github.com/google/glazier/tree/master/doc/setup)?

**Comment by kshithijiyer** [comment]
Yes! But I feel it doesn't cover the usage properly. Think from a layman perspective.

**Comment by TsekNet** [comment]
We'll look into this.

**Comment by TsekNet** [comment]
We've updated the README to clarify: https://github.com/google/glazier#getting-started
