### ISSUE TITLE
Documentation Issue - Broken links

### ISSUE THREAD

**Issue by supremeicecreme** [google/glazier#326]
## Context of the Issue
Reading through the Setup Guide, there are a handful of broken links, mostly to the examples.
https://google.github.io/glazier/setup/

## Detailed Description
On the above specified page, the examples for the `winpeshl.ini` file and the `unattend.xml` file are broken, along with the Registry Keys we need to modify to make Windows auto login and then launch Glazier again each time, and then reset back to their default values at the end.

I can't seem to find these pages through my quick look through, but it should probably be fixed soon!

**Comment by TsekNet** [comment]
Hey @supremeicecreme - thanks for reporting this issue. Looks like since the examples are not in the docs/ directory, we can't use relative links to reference them, and will have to link to them directly. Will get this fixed ASAP.

**Comment by TsekNet** [comment]
Fixed in #327
