### ISSUE TITLE
Documentation Request: please add example for using registry.SetString()

### ISSUE THREAD

**Issue by discentem** [google/glazier#352]
I saw that you added an example for taskmaster.Trigger (thank you!) so I hoping you could drop in an example for registry.SetString() as well.

I got it working but had to tinker with it for a bit. Here's a quick sanitized example but please let me know if can provide a fully working one and I'd be happy to do so. 

https://gist.github.com/discentem/583f141b95e2055f4e1d047dedb52357

**Comment by TsekNet** [comment]
Can you clarify what you're trying to accomplish with SetString? SetString just sets a registry value, and accepts the args as specified in the function. It does what the name implies: set's a REG_SZ string value.

https://github.com/google/glazier/blob/b63f89f9c53832191ce40719357906953270cd59/go/registry/registry.go#L100

Here's a simple example:

```go
if err := registry.SetString(`SOFTWARE\Glazier`, "testkey", "testval"); err != nil {
  return fmt.Errorf(`Failed to set %s\%s = %q: %w`, `SOFTWARE\Glazier`, "testkey", "testval", err)
}
logger.Infof(`Set %s\%s = %s.`, `SOFTWARE\Glazier`, "testkey", "testval")
```

**Comment by discentem** [comment]
This is a totally fair question. The example I provided is very specific to what I happen to be doing but isn't relevant to general usage of registry.SetString(). Your example looks good 👍

**Comment by TsekNet** [comment]
Sounds good, feel free to reopen this issue or create a new one if you continue to run into any issues!
